version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - '8080:8080'
    env_file:
      - app.env
    volumes:
      - ./app.env:/app/app.env # Volume mount for config
    environment:
      - GIN_MODE=release
    restart: unless-stopped
