name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: shravan146/auth-service
      IMAGE_TAG: build-${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        run: |
          ls -la  # Debug: List files to verify checkout
          docker build -t ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} -f Dockerfile ./server
        working-directory: ./server
      - name: Push Docker image to Dockerhub
        run: docker push ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
